import type { ClientNotification } from "./types"

export const MOCK_NOTIFICATIONS: ClientNotification[] = [
  {
    id: "1",
    clientId: "CLI-4521",
    clientName: "Marcus Rodriguez",
    riskLevel: "high",
    totalTransactions: 47,
    totalAmount: 2450000,
    flaggedTransactions: 12,
    lastActivity: "2024-01-19",
    alertType: "Structuring Pattern",
    country: "Panama",
    accountType: "Business",
    transactions: [
      {
        id: "TXN-001",
        date: "2024-01-19",
        amount: 9800,
        type: "Cash Deposit",
        location: "Panama City",
        description: "Cash deposit - Branch 401",
        riskScore: 8.5,
      },
      {
        id: "TXN-002",
        date: "2024-01-19",
        amount: 9750,
        type: "Cash Deposit",
        location: "Panama City",
        description: "Cash deposit - Branch 402",
        riskScore: 8.7,
      },
      {
        id: "TXN-003",
        date: "2024-01-18",
        amount: 9900,
        type: "Wire Transfer",
        location: "Colon",
        description: "International wire - Shell Company Ltd",
        riskScore: 9.2,
      },
    ],
  },
  {
    id: "2",
    clientId: "CLI-7890",
    clientName: "Sarah Chen",
    riskLevel: "high",
    totalTransactions: 23,
    totalAmount: 890000,
    flaggedTransactions: 8,
    lastActivity: "2024-01-18",
    alertType: "Geographic Anomaly",
    country: "Singapore",
    accountType: "Personal",
    transactions: [
      {
        id: "TXN-004",
        date: "2024-01-18",
        amount: 45000,
        type: "Wire Transfer",
        location: "Singapore",
        description: "Wire to offshore account",
        riskScore: 7.8,
      },
      {
        id: "TXN-005",
        date: "2024-01-17",
        amount: 32000,
        type: "ATM Withdrawal",
        location: "Dubai",
        description: "ATM withdrawal - High-risk jurisdiction",
        riskScore: 8.1,
      },
    ],
  },
  {
    id: "3",
    clientId: "CLI-1234",
    clientName: "Ahmed Al-Rashid",
    riskLevel: "medium",
    totalTransactions: 156,
    totalAmount: 1200000,
    flaggedTransactions: 5,
    lastActivity: "2024-01-17",
    alertType: "Velocity Alert",
    country: "UAE",
    accountType: "Business",
    transactions: [
      {
        id: "TXN-006",
        date: "2024-01-17",
        amount: 25000,
        type: "Business Transfer",
        location: "Dubai",
        description: "Business payment - Construction materials",
        riskScore: 5.2,
      },
    ],
  },
  {
    id: "4",
    clientId: "CLI-5678",
    clientName: "Elena Volkov",
    riskLevel: "low",
    totalTransactions: 34,
    totalAmount: 450000,
    flaggedTransactions: 2,
    lastActivity: "2024-01-16",
    alertType: "PEP Monitoring",
    country: "Russia",
    accountType: "Personal",
    transactions: [
      {
        id: "TXN-007",
        date: "2024-01-16",
        amount: 15000,
        type: "Investment",
        location: "Moscow",
        description: "Investment portfolio deposit",
        riskScore: 3.5,
      },
    ],
  },
  {
    id: "5",
    clientId: "CLI-9999",
    clientName: "David Thompson",
    riskLevel: "medium",
    totalTransactions: 89,
    totalAmount: 750000,
    flaggedTransactions: 6,
    lastActivity: "2024-01-15",
    alertType: "Unusual Pattern",
    country: "United States",
    accountType: "Business",
    transactions: [
      {
        id: "TXN-008",
        date: "2024-01-15",
        amount: 28000,
        type: "Wire Transfer",
        location: "New York",
        description: "Business payment - Consulting services",
        riskScore: 4.2,
      },
    ],
  },
]

export const INITIAL_AI_MESSAGE = {
  id: "1",
  type: "ai" as const,
  content:
    'Welcome to the AML Intelligence Platform. I can help you analyze and investigate suspicious activities using natural language. Try asking me things like "Show me high-risk clients" or "Find clients with unusual transaction patterns" and I\'ll provide both filtering and investigative insights.',
  timestamp: new Date(),
  insights: [
    "Currently monitoring 5 clients across multiple jurisdictions",
    "2 high-risk cases require immediate attention",
    "Total flagged transaction volume: $4.99M",
  ],
}
